{
 "title": "stats dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"profile-management\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registered Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "profile_management_users_count{service=\"profile-management\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signup Success Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(profile_management_signups_total{service=\"profile-management\",result=\"success\"}[5m]))\n/\nclamp_min(sum(rate(profile_management_signups_total{service=\"profile-management\"}[5m])), 1e-9)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Login Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(rate(profile_management_signins_total{service=\"profile-management\",result=\"success\"}[5m]))\n/\nclamp_min(sum(rate(profile_management_signins_total{service=\"profile-management\"}[5m])), 1e-9)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}